# Generated by Django 5.1 on 2024-09-20 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_tag_post_tags"),
    ]

    operations = [
        migrations.AddField(
            model_name="tag",
            name="slug",
            field=models.SlugField(default="default-slug", unique=True),
        ),
    ]
