# Generated by Django 4.1.6 on 2024-08-06 21:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("bookshelf", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_year",
            field=models.IntegerField(),
        ),
    ]
